name: 'Pull Request Labeler'
description: 'Automatically labels pull requests based on branch name'
author: 'Hannah Thankam Alex'

# Define your inputs here.
inputs:
  branch-pattern:
    description: 'Branch pattern to label mapping (JSON string)'
    required: true

runs:
  using: 'node24'
  main: 'dist/index.js'
