name: 'Nx Cloud Skipper'
description: 'Run nx commands with fallback to --no-cloud if they fail'
author: 'Robson Oliveira dos Santos'

branding:
  icon: skip-forward
  color: black

inputs:
  command:
    description: |-
      Arguments to pass to the npx nx command (e.g., "affected -t lint test build")
    required: true
  errorMessages:
    description: |-
      List of error messages to detect for retry with --no-cloud.
      These are must be newline-separated. Inputs that contain separators must be escaped with
      a backslash (e.g. \, or \\n) unless quoted. Any leading or trailing whitespace is trimmed
      unless values are quoted.
      Example:

      ```yaml
      errorMessages: |-
        Workspace is unable to be authorized
        exceeding the FREE plan
      ```
    required: false
    default: |-
      Workspace is unable to be authorized
      exceeding the FREE plan

outputs:
  status:
    description: 'Status of the action (success/failure)'

runs:
  using: node20
  main: dist/index.js
