name: 'publish-pr-comment'
description: 'Publish results to PR issues comments'
author: 'core3'
branding:
  icon: 'crosshair'  
  color: 'green'
inputs:
  fileName: 
    required: false
    description: 'file to post as comment'
  text:
    required: false
    description: 'text to post'
  repo:
    required: true
    description: 'target repository ( github.repository ) '
  pull_request_id:
    required: true
    description: 'pull request id ( github.event.issue.number )"'
  matrix_os:
    required: false
    description: 'if job is part or matrix strategy, current os (matris.os))'
  matrix_node:
    required: false
    description: 'if job is part or matrix strategy, current node-version (matris.node-version))'
runs:
  using: 'node12'
  main: 'dist/index.js'
