name: CODEOWNERS coverage checker
description:
  Checks if all files in the repository are covered by the CODEOWNERS file.
author: joelharkes

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  include-gitignore:
    description: Wether or not to exclude files from .gitignore.
    required: false
    default: 'false'
  ignore-default:
    description: Wether to ignore the default * CODEOWNERS line.
    required: false
    default: 'false'
  files:
    description: Files to check, can be used to only check git modified files.
    required: false

# Define your outputs here.
outputs:

runs:
  using: node20
  main: dist/index.js
